### ISSUE TITLE
`register_wallet` fails on Ledger Simulator

### ISSUE THREAD

**Issue by wszdexdrf** [wizardsardine/async-hwi#29]
I was hoping to create a test for `register_wallet` when I encountered this bug. The code is as follows:

```
let policy = "pk([5c9e228d/44'/0'/0']xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy/**)";
hw.register_wallet("Ledger", &policy).await.unwrap();
```
This results in a panic on the second line with message:
```
called `Result::unwrap()` on an `Err` value: Device("Device {\n    command: 2,\n    status: IncorrectData,\n}")
```

The ledger is initialized with seed `all all all all all all all all all all all all`. The fingerprint and xpub in the policy match with the ones reported by other async-hwi functions (and the SLIP-0014 specification)

**Comment by edouardparis** [comment]
Hello, thank you for your interest in the library.
`pk` is used with raw public key, maybe do you mean `pkh` ?

**Comment by wszdexdrf** [comment]
> pk is used with raw public key, maybe do you mean pkh ?

Yes, I am sorry I made a mistake while copying the code to this issue. The error is for `let policy = "pkh(...`

**Comment by edouardparis** [comment]
I tried to reproduce the problem with my own seed and the testnet bitcoin app and I reported an issue to the ledger team (https://github.com/LedgerHQ/app-bitcoin-new/issues/129), can you confirm me that your bitcoin app version is > 2.1.0 ?
Please, the policy you are using does not require registration, so I hope it does not block you

**Comment by wszdexdrf** [comment]
> can you confirm me that your bitcoin app version is > 2.1.0 ?

Yes indeed the version is exactly 2.1. I got the app from [here](https://github.com/LedgerHQ/speculos/blob/develop/apps/nanos%23btc-test%232.1%231c8db8da.elf)

**Comment by bigspider** [comment]
Oh, that's a very old version (I think it's 2.0.1), that is there to test speculos rather than to test bitcoin.
The 2.1 in the filename refers to the firmware version (2.1 for NanoS).

We don't have stable places to distribute compiled elfs, I suggest building from the repository if you can.
