### ISSUE TITLE
Error during policy registration is not handled by Specter client

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/async-hwi#34]
See https://github.com/wizardsardine/liana/issues/532

**Comment by jp1ac4** [comment]
Hi @edouardparis, as far as I can tell, the response received from the Specter device when adding a wallet in both Confirm and Cancel case is `"error: User cancelled"`, so it doesn't seem like we can tell whether or not the user really cancelled.

Could it be that Specter is processing the request correctly but returning the wrong response in https://github.com/cryptoadvance/specter-diy/blob/master/src/hosts/usb.py#L80?

**Comment by edouardparis** [comment]
Yes, I think you are right. It is a problem on the cryptoadvance side also.
Do you mind to create an issue in the cryptoadvance repo ?

**Comment by jp1ac4** [comment]
Sure, I'll create an issue there.

**Comment by jp1ac4** [comment]
A new release has now been published: https://github.com/cryptoadvance/specter-diy/releases/tag/v1.9.0.

**Comment by jp1ac4** [comment]
I think this is working fine now following the release of Specter v1.9.0 together with some changes from #65.

I added some `println!()` statements to check messages received from Specter while running descriptor registration in the Liana installer:
- if I click Confirm, the message received from Specter is "success" and a green tick appears in the Liana installer descriptor registration step
- if I click Cancel, the message received is "error: User cancelled" and a green tick does not appear

So I think this issue can be closed now :relieved:

**Comment by edouardparis** [comment]
Thanks for checking !
